name: Smoke Tests

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php:
          - '7.4'
          - '8.1'
        deps:
          - highest
          - lowest
      fail-fast: true
    name: PHP ${{ matrix.php }} / ${{ matrix.deps }}
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@d30ad8b1843ace22e6698ab99bbafaa747b6bd0d
        with:
          php-version: ${{ matrix.php }}
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Enable assertions
        run: echo 'zend.assertions=1' | sudo tee /etc/php/${{ matrix.php }}/cli/conf.d/assert.ini >/dev/null
      - name: "Issue #18"
        run: |
          export COMPOSER_CACHE_DIR="$(composer global config cache-dir)"
          export COMPOSER_HOME="$(mktemp -d)"
          composer global config allow-plugins.cs278/composer-audit true
          composer global config repositories.0 path "$(pwd)"
          composer global require cs278/composer-audit:@dev
          cd "$(mktemp -d)"
          composer require --no-install cs278/mktemp
          composer security-audit -vvv
